version: 2.1

orbs:
  win: circleci/windows@2.4.0

defaults: &defaults
  parameters:
    jdk_version:
      type: string
      default: ""
    node_version:
      type: string
      default: ""
  working_directory: ~/snyk-sbt-plugin

windows_defaults: &windows_defaults
  environment:
    npm_config_loglevel: silent
  executor:
    name: win/default

commands:
  install_deps:
    description: Install dependencies
    steps:
      - run:
          name: Install dependencies
          command: npm install
  install_node_npm:
    description: Install correct Node version
    parameters:
      node_version:
        type: string
        default: ""
    steps:
      - run:
          name: Install correct version of Node
          command: nvm install << parameters.node_version >>
      - run:
          name: Use correct version of Node
          command: nvm use << parameters.node_version >>
  show_node_version:
    description: Log Node and npm version
    steps:
      - run:
          name: Node version
          command: node --version
      - run:
          name: NPM version
          command: npm --version
  show_java_version:
    description: Log Java version
    steps:
      - run:
          name: Java version
          command: java -version
  install_sbt_windows:
    description: Install sbt
    steps:
      - run: choco install sbt
  install_sdkman:
    description: Install SDKMAN
    steps:
      - run:
          name: Installing SDKMAN
          command: |
            curl -s "https://get.sdkman.io?rcupdate=false" | bash
            echo -e '\nsource "/home/circleci/.sdkman/bin/sdkman-init.sh"' >> $BASH_ENV
            source $BASH_ENV
  install_sbt_unix:
    description: Install sbt
    steps:
      - run: sdk install sbt
  install_jdk_unix:
    description: Install JDK
    parameters:
      jdk_version:
        type: string
        default: ""
    steps:
      - run:
          name: Installing JDK
          command: sdk install java $(sdk list java | grep -o -m1 "<< parameters.jdk_version >>\.[0-9\.]\+hs-adpt")
  install_jdk_windows:
    description: Install JDK
    parameters:
      jdk_version:
        type: string
        default: ""
    steps:
      - run:
          name: Installing JDK
          command: choco install openjdk<< parameters.jdk_version >>

jobs:
  lint:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    steps:
      - checkout
      - install_deps
      - show_node_version
      - show_java_version
      - run:
          name: Run lint
          command: npm run lint

  test-windows:
    <<: *defaults
    <<: *windows_defaults
    environment:
      JDK: << parameters.jdk_version >>
    steps:
      - run: git config --global core.autocrlf false
      - checkout
      - install_node_npm:
          node_version: << parameters.node_version >>
      - install_jdk_windows:
          jdk_version: << parameters.jdk_version >>
      - install_sbt_windows
      - install_deps
      - show_node_version
      - show_java_version
      - run:
          name: Run tests
          command: npm test

  test-unix:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    environment:
      JDK: << parameters.jdk_version >>
    steps:
      - checkout
      - install_sdkman
      - install_jdk_unix:
          jdk_version: << parameters.jdk_version >>
      - install_sbt_unix
      - install_deps
      - show_node_version
      - run:
          name: Run tests
          command: npm test

  release:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    steps:
      - checkout
      - install_deps
      - run: sudo npm i -g semantic-release @semantic-release/exec pkg
      - run:
          name: Publish to GitHub
          command: semantic-release

  workflows:
    version: 2
    test_and_release:
      jobs:
      - lint:
          name: Lint
          context: nodejs-install
          node_version: "10"
          filters:
            branches:
              ignore:
                - master

      # UNIX tests
      - test-unix:
          name: Unix Tests for SBT JDK=9 Node=6
          context: nodejs-install
          jdk_version: "9"
          node_version: "6"
          requires:
            - Lint
          filters:
            branches:
              ignore:
                - master

      # Windows tests
      - test-windows:
          name: Windows Tests for SBT JDK=9 Node=6
          context: nodejs-install
          jdk_version: "9"
          node_version: "6"
          requires:
            - Lint
          filters:
            branches:
              ignore:
                - master

      # Release
      - release:
          name: Release
          context: nodejs-app-release
          node_version: "8"
          filters:
            branches:
              only:
                - master